/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_icecp_node_security_tpm_tpm20_Tss2_0Nativeinterface */

#ifndef _Included_com_intel_icecp_node_security_tpm_tpm20_Tss2_0Nativeinterface
#define _Included_com_intel_icecp_node_security_tpm_tpm20_Tss2_0Nativeinterface
#ifdef __cplusplus
extern "C" {
#endif
    /*
     * Class:     com_intel_icecp_node_security_tpm_tpm20_Tss2_0Nativeinterface
     * Method:    InitTpm
     * Signature: ()V
     */
    JNIEXPORT void JNICALL Java_com_intel_icecp_node_security_tpm_tpm20_Tss2_10Nativeinterface_InitTpm
    (JNIEnv *, jclass);

    /*
     * Class:     com_intel_icecp_node_security_tpm_tpm20_Tss2_0Nativeinterface
     * Method:    CreatePrimaryKey
     * Signature: (I)V
     */
    JNIEXPORT void JNICALL Java_com_intel_icecp_node_security_tpm_tpm20_Tss2_10Nativeinterface_CreatePrimaryKey
    (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
