/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_icecp_node_security_tpm_tpm12_Tss1_2NativeInterface */

#ifndef _Included_com_intel_icecp_node_security_tpm_tpm12_Tss1_2NativeInterface
#define _Included_com_intel_icecp_node_security_tpm_tpm12_Tss1_2NativeInterface
#ifdef __cplusplus
extern "C" {
#endif
    /*
     * Class:     com_intel_icecp_node_security_tpm_tpm12_Tss1_2NativeInterface
     * Method:    createTpmContext
     * Signature: ()I
     */
    JNIEXPORT jint JNICALL Java_com_intel_icecp_node_security_tpm_tpm12_Tss1_12NativeInterface_createTpmContext
    (JNIEnv *, jclass);

    /*
     * Class:     com_intel_icecp_node_security_tpm_tpm12_Tss1_2NativeInterface
     * Method:    loadRegisteredKeys
     * Signature: (I)V
     */
    JNIEXPORT void JNICALL Java_com_intel_icecp_node_security_tpm_tpm12_Tss1_12NativeInterface_loadRegisteredKeys
    (JNIEnv *, jclass, jint);

    /*
     * Class:     com_intel_icecp_node_security_tpm_tpm12_Tss1_2NativeInterface
     * Method:    deleteTpmContext
     * Signature: (I)V
     */
    JNIEXPORT void JNICALL Java_com_intel_icecp_node_security_tpm_tpm12_Tss1_12NativeInterface_deleteTpmContext
    (JNIEnv *, jclass, jint);

    /*
     * Class:     com_intel_icecp_node_security_tpm_tpm12_Tss1_2NativeInterface
     * Method:    setTpmOwnerPriviledges
     * Signature: (I[B)V
     */
    JNIEXPORT void JNICALL Java_com_intel_icecp_node_security_tpm_tpm12_Tss1_12NativeInterface_setTpmOwnerPriviledges
    (JNIEnv *, jclass, jint, jbyteArray);

    /*
     * Class:     com_intel_icecp_node_security_tpm_tpm12_Tss1_2NativeInterface
     * Method:    createOwnerDelegation
     * Signature: (I)[B
     */
    JNIEXPORT jbyteArray JNICALL Java_com_intel_icecp_node_security_tpm_tpm12_Tss1_12NativeInterface_createOwnerDelegation
    (JNIEnv *, jclass, jint);

    /*
     * Class:     com_intel_icecp_node_security_tpm_tpm12_Tss1_2NativeInterface
     * Method:    loadSrk
     * Signature: (I[B)V
     */
    JNIEXPORT void JNICALL Java_com_intel_icecp_node_security_tpm_tpm12_Tss1_12NativeInterface_loadSrk
    (JNIEnv *, jclass, jint, jbyteArray);

    /*
     * Class:     com_intel_icecp_node_security_tpm_tpm12_Tss1_2NativeInterface
     * Method:    calculateHash
     * Signature: (I[B)[B
     */
    JNIEXPORT jbyteArray JNICALL Java_com_intel_icecp_node_security_tpm_tpm12_Tss1_12NativeInterface_calculateHash
    (JNIEnv *, jclass, jint, jbyteArray);

    /*
     * Class:     com_intel_icecp_node_security_tpm_tpm12_Tss1_2NativeInterface
     * Method:    createKey
     * Signature: (IIIIIIIZ[B)[B
     */
    JNIEXPORT jbyteArray JNICALL Java_com_intel_icecp_node_security_tpm_tpm12_Tss1_12NativeInterface_createKey
    (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jboolean, jbyteArray);

    /*
     * Class:     com_intel_icecp_node_security_tpm_tpm12_Tss1_2NativeInterface
     * Method:    unregisterKey
     * Signature: (I[BI)V
     */
    JNIEXPORT void JNICALL Java_com_intel_icecp_node_security_tpm_tpm12_Tss1_12NativeInterface_unregisterKey
    (JNIEnv *, jclass, jint, jbyteArray, jint);

    /*
     * Class:     com_intel_icecp_node_security_tpm_tpm12_Tss1_2NativeInterface
     * Method:    getPEMPublicKeyByUUID
     * Signature: (I[B)[B
     */
    JNIEXPORT jbyteArray JNICALL Java_com_intel_icecp_node_security_tpm_tpm12_Tss1_12NativeInterface_getPEMPublicKeyByUUID
    (JNIEnv *, jclass, jint, jbyteArray);

    /*
     * Class:     com_intel_icecp_node_security_tpm_tpm12_Tss1_2NativeInterface
     * Method:    getPEMEKPublicKey
     * Signature: (I)[B
     */
    JNIEXPORT jbyteArray JNICALL Java_com_intel_icecp_node_security_tpm_tpm12_Tss1_12NativeInterface_getPEMEKPublicKey
    (JNIEnv *, jclass, jint);

    /*
     * Class:     com_intel_icecp_node_security_tpm_tpm12_Tss1_2NativeInterface
     * Method:    extractPEMPublicKeyFromTPMPubKeyBlob
     * Signature: (I[B)[B
     */
    JNIEXPORT jbyteArray JNICALL Java_com_intel_icecp_node_security_tpm_tpm12_Tss1_12NativeInterface_extractPEMPublicKeyFromTPMPubKeyBlob
    (JNIEnv *, jclass, jint, jbyteArray);

    /*
     * Class:     com_intel_icecp_node_security_tpm_tpm12_Tss1_2NativeInterface
     * Method:    extractPEMPublicKeyFromTPMKeyBlob
     * Signature: (I[B)[B
     */
    JNIEXPORT jbyteArray JNICALL Java_com_intel_icecp_node_security_tpm_tpm12_Tss1_12NativeInterface_extractPEMPublicKeyFromTPMKeyBlob
    (JNIEnv *, jclass, jint, jbyteArray);

    /*
     * Class:     com_intel_icecp_node_security_tpm_tpm12_Tss1_2NativeInterface
     * Method:    flushTpmOwnerPriviledges
     * Signature: (I)V
     */
    JNIEXPORT void JNICALL Java_com_intel_icecp_node_security_tpm_tpm12_Tss1_12NativeInterface_flushTpmOwnerPriviledges
    (JNIEnv *, jclass, jint);

    /*
     * Class:     com_intel_icecp_node_security_tpm_tpm12_Tss1_2NativeInterface
     * Method:    sealData
     * Signature: (I[B[I[B)[B
     */
    JNIEXPORT jbyteArray JNICALL Java_com_intel_icecp_node_security_tpm_tpm12_Tss1_12NativeInterface_sealData
    (JNIEnv *, jclass, jint, jbyteArray, jintArray, jbyteArray);

    /*
     * Class:     com_intel_icecp_node_security_tpm_tpm12_Tss1_2NativeInterface
     * Method:    unsealData
     * Signature: (I[B[B[B)[B
     */
    JNIEXPORT jbyteArray JNICALL Java_com_intel_icecp_node_security_tpm_tpm12_Tss1_12NativeInterface_unsealData
    (JNIEnv *, jclass, jint, jbyteArray, jbyteArray, jbyteArray);

    /*
     * Class:     com_intel_icecp_node_security_tpm_tpm12_Tss1_2NativeInterface
     * Method:    pcrExtend
     * Signature: (II[B)[B
     */
    JNIEXPORT jbyteArray JNICALL Java_com_intel_icecp_node_security_tpm_tpm12_Tss1_12NativeInterface_pcrExtend
    (JNIEnv *, jclass, jint, jint, jbyteArray);

    /*
     * Class:     com_intel_icecp_node_security_tpm_tpm12_Tss1_2NativeInterface
     * Method:    getRandomBytes
     * Signature: (II)[B
     */
    JNIEXPORT jbyteArray JNICALL Java_com_intel_icecp_node_security_tpm_tpm12_Tss1_12NativeInterface_getRandomBytes
    (JNIEnv *, jclass, jint, jint);

    /*
     * Class:     com_intel_icecp_node_security_tpm_tpm12_Tss1_2NativeInterface
     * Method:    generateIdentityRequest
     * Signature: (I[B[B[B)[B
     */
    JNIEXPORT jbyteArray JNICALL Java_com_intel_icecp_node_security_tpm_tpm12_Tss1_12NativeInterface_generateIdentityRequest
    (JNIEnv *, jclass, jint, jbyteArray, jbyteArray, jbyteArray);

    /*
     * Class:     com_intel_icecp_node_security_tpm_tpm12_Tss1_2NativeInterface
     * Method:    verifyIdentityRequestBinding
     * Signature: (I[B[B[B)[B
     */
    JNIEXPORT jbyteArray JNICALL Java_com_intel_icecp_node_security_tpm_tpm12_Tss1_12NativeInterface_verifyIdentityRequestBinding
    (JNIEnv *, jclass, jint, jbyteArray, jbyteArray, jbyteArray);

    /*
     * Class:     com_intel_icecp_node_security_tpm_tpm12_Tss1_2NativeInterface
     * Method:    createAttestationResponse
     * Signature: (I[B[B[B)[B
     */
    JNIEXPORT jbyteArray JNICALL Java_com_intel_icecp_node_security_tpm_tpm12_Tss1_12NativeInterface_createAttestationResponse
    (JNIEnv *, jclass, jint, jbyteArray, jbyteArray, jbyteArray);

    /*
     * Class:     com_intel_icecp_node_security_tpm_tpm12_Tss1_2NativeInterface
     * Method:    activateIdentity
     * Signature: (I[B[B)[B
     */
    JNIEXPORT jbyteArray JNICALL Java_com_intel_icecp_node_security_tpm_tpm12_Tss1_12NativeInterface_activateIdentity
    (JNIEnv *, jclass, jint, jbyteArray, jbyteArray);

    /*
     * Class:     com_intel_icecp_node_security_tpm_tpm12_Tss1_2NativeInterface
     * Method:    createCredentials
     * Signature: (I[B[B[B)[B
     */
    JNIEXPORT jbyteArray JNICALL Java_com_intel_icecp_node_security_tpm_tpm12_Tss1_12NativeInterface_createCredentials
    (JNIEnv *, jclass, jint, jbyteArray, jbyteArray, jbyteArray);

    /*
     * Class:     com_intel_icecp_node_security_tpm_tpm12_Tss1_2NativeInterface
     * Method:    quote
     * Signature: (I[B[B[I)[B
     */
    JNIEXPORT jbyteArray JNICALL Java_com_intel_icecp_node_security_tpm_tpm12_Tss1_12NativeInterface_quote
    (JNIEnv *, jclass, jint, jbyteArray, jbyteArray, jintArray);

    /*
     * Class:     com_intel_icecp_node_security_tpm_tpm12_Tss1_2NativeInterface
     * Method:    verifyQuote
     * Signature: (I[B[B[B[B[B)V
     */
    JNIEXPORT void JNICALL Java_com_intel_icecp_node_security_tpm_tpm12_Tss1_12NativeInterface_verifyQuote
    (JNIEnv *, jclass, jint, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
